(function(){
  const TEXT_KEY='labPortfolioUniversal', IMG_KEY='labPortfolioImages', DRAFT_TEXT='labPortfolioUniversalDraft', PUB_TEXT='labPortfolioUniversalPublished', DRAFT_IMG='labPortfolioImagesDraft', PUB_IMG='labPortfolioImagesPublished';
  const EDIT=location.search.includes('edit=1'), PREVIEW=location.search.includes('preview=1');
  let toolbar,pop,current;
  const store=(k,fallback={})=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(fallback))}catch(e){return fallback}};
  const textKey=EDIT||PREVIEW?DRAFT_TEXT:PUB_TEXT, imgKey=EDIT||PREVIEW?DRAFT_IMG:PUB_IMG;
  function loadText(){return store(textKey,store(TEXT_KEY,{}))} function loadImg(){return store(imgKey,store(IMG_KEY,{}))}
  function pathFor(node){const parts=[];let n=node;while(n&&n.nodeType===1){let i=1,s=n.previousElementSibling;while(s){if(s.tagName===n.tagName)i++;s=s.previousElementSibling}parts.unshift(n.tagName.toLowerCase()+':nth-of-type('+i+')');n=n.parentElement}return parts.join('>')}
  function textNodes(){const out=[],counts=new Map(),w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){const p=n.parentElement;if(!p||['SCRIPT','STYLE','NOSCRIPT'].includes(p.tagName)||p.closest('[data-cms-ignore]')||p.closest('#cms-edit-toolbar,#cms-edit-pop'))continue;const raw=n.nodeValue||'';if(!raw.trim())continue;const path=pathFor(p),idx=counts.get(path)||0;counts.set(path,idx+1);out.push({path,index:idx,key:path+'#'+idx,text:raw,node:n})}return out}
  function imgItems(){return [...document.querySelectorAll('img')].filter(x=>!x.closest('[data-cms-ignore]')).map(img=>({key:pathFor(img),node:img,src:img.getAttribute('src')||''}))}
  function apply(){const t=loadText(),im=loadImg();textNodes().forEach(x=>{if(Object.prototype.hasOwnProperty.call(t,x.key))x.node.nodeValue=t[x.key]});imgItems().forEach(x=>{if(im[x.key])x.node.src=im[x.key]})}
  function getItems(){const t=loadText();return textNodes().map((x,i)=>({...x,value:Object.prototype.hasOwnProperty.call(t,x.key)?t[x.key]:x.text,index:i+1}))}
  function save(items){const t=loadText();items.forEach(x=>t[x.key]=x.value);localStorage.setItem(DRAFT_TEXT,JSON.stringify(t));return t}
  function addStyles(){if(document.getElementById('cms-edit-style'))return;const s=document.createElement('style');s.id='cms-edit-style';s.textContent=`body.cms-edit-mode [data-cms-editable]{outline:1px dashed rgba(37,99,235,.38);outline-offset:3px;cursor:text;background:rgba(37,99,235,.025)} body.cms-edit-mode [data-cms-editable]:hover{outline:2px solid #2563eb;background:rgba(37,99,235,.07)} body.cms-edit-mode img[data-cms-img]{outline:2px dashed #7c3aed;outline-offset:4px;cursor:pointer} #cms-edit-toolbar{position:fixed;z-index:2147483646;left:50%;bottom:18px;transform:translateX(-50%);display:flex;align-items:center;gap:7px;padding:10px 12px;border:1px solid #cbd5e1;border-radius:14px;background:#fff;box-shadow:0 10px 35px rgba(15,23,42,.2);font:14px system-ui,sans-serif;white-space:nowrap} #cms-edit-toolbar button{border:1px solid #cbd5e1;background:#f8fafc;border-radius:9px;padding:8px 11px;cursor:pointer} #cms-edit-toolbar .primary{background:#0f172a;color:#fff;border-color:#0f172a} #cms-edit-status{color:#64748b;min-width:110px} #cms-edit-pop{position:fixed;z-index:2147483647;width:min(520px,calc(100vw - 30px));padding:12px;background:#fff;border:1px solid #cbd5e1;border-radius:12px;box-shadow:0 15px 45px rgba(15,23,42,.22);font:14px system-ui,sans-serif} #cms-edit-pop textarea,#cms-edit-pop input{width:100%;box-sizing:border-box;border:1px solid #94a3b8;border-radius:8px;padding:9px;font:14px/1.5 system-ui,sans-serif} #cms-edit-pop textarea{min-height:100px;resize:vertical} #cms-edit-pop .row{display:flex;justify-content:flex-end;gap:7px;margin-top:8px} #cms-edit-pop button{border:1px solid #cbd5e1;background:#f8fafc;border-radius:8px;padding:7px 10px;cursor:pointer} #cms-edit-pop .ok{background:#2563eb;color:#fff;border-color:#2563eb}`;document.head.appendChild(s)}
  function status(t){const e=document.getElementById('cms-edit-status');if(e)e.textContent=t}
  function popAt(el,html){if(pop)pop.remove();pop=document.createElement('div');pop.id='cms-edit-pop';pop.innerHTML=html;document.body.appendChild(pop);const r=el.getBoundingClientRect();let left=Math.min(Math.max(15,r.left),innerWidth-pop.offsetWidth-15),top=r.bottom+12;if(top+pop.offsetHeight>innerHeight-15)top=Math.max(15,r.top-pop.offsetHeight-12);pop.style.left=left+'px';pop.style.top=top+'px';return pop}
  function showText(item){const p=popAt(item.node.parentElement,'<div style="font-weight:700;margin-bottom:7px">문구 수정</div><textarea></textarea><div class="row"><button id="cancel">취소</button><button id="ok" class="ok">적용</button></div>'),ta=p.querySelector('textarea');ta.value=item.node.nodeValue;ta.focus();ta.select();p.querySelector('#cancel').onclick=()=>p.remove();p.querySelector('#ok').onclick=()=>{item.node.nodeValue=ta.value;const o=loadText();o[item.key]=ta.value;localStorage.setItem(DRAFT_TEXT,JSON.stringify(o));p.remove();status('임시저장됨')};ta.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')p.querySelector('#ok').click();if(e.key==='Escape')p.remove()}}
  function showImage(img){const p=popAt(img,'<div style="font-weight:700;margin-bottom:7px">이미지 교체</div><input id="url" placeholder="이미지 URL 또는 파일 선택"><input id="file" type="file" accept="image/*" style="margin-top:8px"><div class="row"><button id="cancel">취소</button><button id="ok" class="ok">적용</button></div>');const url=p.querySelector('#url');url.value=img.src;const file=p.querySelector('#file');file.onchange=()=>{const f=file.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>url.value=rd.result;rd.readAsDataURL(f)};p.querySelector('#cancel').onclick=()=>p.remove();p.querySelector('#ok').onclick=()=>{const v=url.value.trim();if(!v)return;p.querySelector('#ok').disabled=true;const o=loadImg();o[pathFor(img)]=v;localStorage.setItem(DRAFT_IMG,JSON.stringify(o));img.src=v;p.remove();status('이미지 임시저장됨')}}
  function enable(){addStyles();document.body.classList.add('cms-edit-mode');toolbar=document.createElement('div');toolbar.id='cms-edit-toolbar';toolbar.innerHTML='<b>홈페이지 편집</b><span id="cms-edit-status">편집 모드</span><button id="save" class="primary">임시저장</button><button id="preview">미리보기</button><button id="publish">공개</button><button id="reset">초기화</button><button id="close">종료</button>';document.body.appendChild(toolbar);
    function refresh(){textNodes().forEach(x=>{x.node.parentElement.dataset.cmsEditable='1';if(!x.node.parentElement.dataset.cmsBound)x.node.parentElement.addEventListener('click',clickText,true);x.node.parentElement.dataset.cmsBound='1'});imgItems().forEach(x=>{x.node.dataset.cmsImg='1';if(!x.node.dataset.cmsBound)x.node.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();showImage(x.node)},true);x.node.dataset.cmsBound='1'})}
    function clickText(e){if(e.target.closest('#cms-edit-toolbar,#cms-edit-pop')||e.target.tagName==='IMG')return;e.preventDefault();e.stopPropagation();const x=textNodes().find(a=>a.node===e.target||a.node.parentElement===e.currentTarget);if(x)showText(x)}
    toolbar.querySelector('#save').onclick=()=>{const t=loadText();localStorage.setItem(DRAFT_TEXT,JSON.stringify(t));localStorage.setItem('labPortfolioUniversal',JSON.stringify(t));const i=loadImg();localStorage.setItem(DRAFT_IMG,JSON.stringify(i));localStorage.setItem('labPortfolioImages',JSON.stringify(i));status('임시저장 완료')};
    toolbar.querySelector('#preview').onclick=()=>window.open(location.pathname+'?preview=1','_blank');
    toolbar.querySelector('#publish').onclick=()=>{if(!confirm('현재 수정 내용을 공개 상태로 반영할까요?'))return;const t=loadText(),i=loadImg();localStorage.setItem(PUB_TEXT,JSON.stringify(t));localStorage.setItem(PUB_IMG,JSON.stringify(i));localStorage.setItem(TEXT_KEY,JSON.stringify(t));localStorage.setItem(IMG_KEY,JSON.stringify(i));localStorage.setItem('labPortfolioUniversalHistory',JSON.stringify([{at:new Date().toISOString(),text:t,images:i},...store('labPortfolioUniversalHistory',[]).slice(0,9)]));status('공개 완료');setTimeout(()=>location.href=location.pathname,500)};
    toolbar.querySelector('#reset').onclick=()=>{if(confirm('임시 수정 내용을 초기화할까요?')){localStorage.removeItem(DRAFT_TEXT);localStorage.removeItem(DRAFT_IMG);location.reload()}};
    toolbar.querySelector('#close').onclick=()=>location.href=location.pathname;
    refresh();let n=0;const timer=setInterval(()=>{refresh();apply();if(++n>20)clearInterval(timer)},400)
  }
  window.CMS_UNIVERSAL={getItems,save,apply,clear:()=>{localStorage.removeItem(TEXT_KEY);localStorage.removeItem(DRAFT_TEXT);localStorage.removeItem(PUB_TEXT);localStorage.removeItem(IMG_KEY);localStorage.removeItem(DRAFT_IMG);localStorage.removeItem(PUB_IMG);location.reload()}};
  window.addEventListener('load',async()=>{
    if(!EDIT && window.CMS_CLOUD?.ready()){try{const row=await window.CMS_CLOUD.getState();if(row?.published_text)localStorage.setItem(PUB_TEXT,JSON.stringify(row.published_text));if(row?.published_images)localStorage.setItem(PUB_IMG,JSON.stringify(row.published_images))}catch(e){console.warn('Cloud text/image read failed.',e)}}
    let n=0,t=setInterval(()=>{apply();if(++n>12)clearInterval(t)},300);if(EDIT)enable()
  });
})();