-- Park Sang-deuk V12 CMS — Supabase schema
-- Run in Supabase SQL Editor. Then create an Auth user and add that email to cms_admins.

create table if not exists public.cms_admins (
  email text primary key,
  created_at timestamptz not null default now()
);
alter table public.cms_admins enable row level security;
drop policy if exists "admin reads own allowlist" on public.cms_admins;
create policy "admin reads own allowlist" on public.cms_admins for select to authenticated
using (lower(email)=lower(coalesce(auth.jwt()->>'email','')));

create table if not exists public.site_published (
  id text primary key,
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);
insert into public.site_published(id) values('main') on conflict(id) do nothing;
alter table public.site_published enable row level security;
drop policy if exists "public reads published" on public.site_published;
create policy "public reads published" on public.site_published for select to anon, authenticated using(id='main');
drop policy if exists "admin updates published" on public.site_published;
create policy "admin updates published" on public.site_published for update to authenticated
using(id='main' and exists(select 1 from public.cms_admins a where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))))
with check(id='main' and exists(select 1 from public.cms_admins a where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))));

create table if not exists public.site_drafts (
  id text primary key,
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);
insert into public.site_drafts(id) values('main') on conflict(id) do nothing;
alter table public.site_drafts enable row level security;
drop policy if exists "admin reads drafts" on public.site_drafts;
create policy "admin reads drafts" on public.site_drafts for select to authenticated
using(exists(select 1 from public.cms_admins a where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))));
drop policy if exists "admin updates drafts" on public.site_drafts;
create policy "admin updates drafts" on public.site_drafts for update to authenticated
using(exists(select 1 from public.cms_admins a where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))))
with check(exists(select 1 from public.cms_admins a where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))));

create table if not exists public.site_revisions (
 id bigint generated by default as identity primary key,
 site_id text not null default 'main',
 content jsonb not null default '{}'::jsonb,
 published_at timestamptz not null default now(),
 published_by uuid references auth.users(id) on delete set null,
 summary jsonb not null default '{}'::jsonb
);
alter table public.site_revisions enable row level security;
drop policy if exists "admin reads revisions" on public.site_revisions;
create policy "admin reads revisions" on public.site_revisions for select to authenticated
using(exists(select 1 from public.cms_admins a where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))));
drop policy if exists "admin creates revisions" on public.site_revisions;
create policy "admin creates revisions" on public.site_revisions for insert to authenticated
with check(auth.uid()=published_by and exists(select 1 from public.cms_admins a where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))));

insert into storage.buckets(id,name,public) values('site-assets','site-assets',true) on conflict(id) do update set public=true;
drop policy if exists "admin reads asset metadata" on storage.objects;
create policy "admin reads asset metadata" on storage.objects for select to authenticated
using(bucket_id='site-assets' and exists(select 1 from public.cms_admins a where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))));
drop policy if exists "admin uploads assets" on storage.objects;
create policy "admin uploads assets" on storage.objects for insert to authenticated
with check(bucket_id='site-assets' and exists(select 1 from public.cms_admins a where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))));
drop policy if exists "admin updates assets" on storage.objects;
create policy "admin updates assets" on storage.objects for update to authenticated
using(bucket_id='site-assets' and exists(select 1 from public.cms_admins a where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))))
with check(bucket_id='site-assets' and exists(select 1 from public.cms_admins a where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))));
drop policy if exists "admin deletes assets" on storage.objects;
create policy "admin deletes assets" on storage.objects for delete to authenticated
using(bucket_id='site-assets' and exists(select 1 from public.cms_admins a where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))));
