const KEY='psV12CMS',DRAFT='psV12CMSDraft',PUB='psV12CMSPublished';let data,current='dashboard';
const tabs=[['dashboard','대시보드'],['profile','프로필/사진'],['problems','문제인식'],['records','주요실적'],['method','방법론/KAIM'],['courses','교육과정'],['works','개발성과/이미지'],['archive','아카이브'],['contact','연락처'],['revisions','버전관리']];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const clone=x=>JSON.parse(JSON.stringify(x));
async function init(){
 const local=localStorage.getItem(KEY);data=local?JSON.parse(local):await (await fetch('../data/site-default.json')).json();
 if(V12_CLOUD.ready()){try{const d=await V12_CLOUD.getDraft();if(d?.content)data=d.content;document.getElementById('cloudStatus').textContent='Supabase 연결 · 관리자 인증 완료'}catch(e){document.getElementById('cloudStatus').textContent='Cloud 초안 불러오기 실패'}}
 document.getElementById('tabs').innerHTML=tabs.map(([k,n])=>`<button data-tab="${k}">${n}</button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{collect();current=b.dataset.tab;panel()});panel()
}
function inp(k,v,type='text'){return `<input data-k="${k}" type="${type}" value="${esc(v)}">`}function ta(k,v){return `<textarea data-k="${k}">${esc(v)}</textarea>`}function card(title,hint,body){return `<div class="card"><h2>${title}</h2><p class="hint">${hint}</p>${body}</div>`}
function panel(){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===current));let h='';
if(current==='dashboard')h=`<div class="dashboard"><div class="dash">교육·워크숍<strong>${esc(data.recordCount)}</strong><span>실시 회차</span></div><div class="dash">교육과정<strong>${data.courses.length}</strong><span>프로그램</span></div><div class="dash">개발성과<strong>${data.works.length}</strong><span>관리 항목</span></div><div class="dash">프로필 사진<strong>${data.profile.portrait?'등록':'미등록'}</strong><span>이미지 상태</span></div></div>`;
if(current==='profile')h=card('프로필 / 이미지','프로필 사진과 로고를 업로드하고 첫 화면의 핵심 문구를 관리합니다.',`<div class="uploadbox"><div class="preview">${data.profile.portrait?`<img src="${esc(data.profile.portrait)}">`:'사진 없음'}</div><div><label>프로필 사진</label><input id="portraitFile" type="file" accept="image/*"><button class="add" id="clearPortrait">사진 삭제</button><label>이름</label>${inp('profile.name',data.profile.name)}<label>영문/키커</label>${inp('profile.kicker',data.profile.kicker)}<label>메인 문장</label>${ta('profile.headline',data.profile.headline)}<label>소개</label>${ta('profile.lead',data.profile.lead)}<label>경력 — 한 줄에 하나</label>${ta('profile.career',data.profile.career.join('\n'))}<label>로고 이미지 경로</label>${inp('profile.logo',data.profile.logo)}</div></div>`);
if(current==='problems')h=card('행정의 문제인식','4개의 문제와 연결 문장을 수정합니다.',data.problems.map((x,i)=>`<div class="grid"><div><label>${i+1}. 제목</label>${inp(`problems.${i}.title`,x.title)}</div><div><label>설명</label>${ta(`problems.${i}.desc`,x.desc)}</div></div>`).join('')+`<label>핵심 연결 문장</label>${inp('problemBridge',data.problemBridge)}`);
if(current==='records')h=card('주요 실적','연도별 테마와 실적을 관리합니다. 실적은 한 줄에 하나씩 입력합니다.',data.records.map((x,i)=>`<div class="row record"><div>${inp(`records.${i}.year`,x.year)}</div><div>${inp(`records.${i}.theme`,x.theme)}</div><div>${ta(`records.${i}.items`,x.items.join('\n'))}</div><button class="del" data-delrecord="${i}">삭제</button></div>`).join('')+`<button class="add" id="addRecord">+ 연도 추가</button><label>총 실시 회차</label>${inp('recordCount',data.recordCount)}`);
if(current==='method')h=card('방법론 / KAIM','5단계 방법론과 KAIM 설명을 관리합니다.',data.method.map((x,i)=>`<label>제${i+1}단계</label>${inp(`method.${i}`,x)}`).join('')+`<label>KAIM 제목</label>${inp('kaim.title',data.kaim.title)}<label>KAIM 설명</label>${ta('kaim.desc',data.kaim.desc)}`);
if(current==='courses')h=card('교육과정','과정명·대상·시간을 관리합니다.',data.courses.map((x,i)=>`<div class="row"><div>${inp(`courses.${i}.name`,x.name)}</div><div>${inp(`courses.${i}.target`,x.target)}</div><div>${inp(`courses.${i}.hours`,x.hours)}</div><span></span><button class="del" data-delcourse="${i}">삭제</button></div>`).join('')+`<button class="add" id="addCourse">+ 과정 추가</button>`);
if(current==='works')h=card('개발성과 / 포트폴리오 이미지','각 개발성과에 대표 이미지를 업로드할 수 있습니다.',data.works.map((x,i)=>`<div class="card"><div class="uploadbox"><div class="preview workpreview">${x.image?`<img src="${esc(x.image)}">`:'이미지 없음'}</div><div><label>제목</label>${inp(`works.${i}.title`,x.title)}<label>설명</label>${ta(`works.${i}.desc`,x.desc)}<label>대표 이미지</label><input type="file" accept="image/*" data-workfile="${i}"><button class="del" data-delwork="${i}">항목 삭제</button></div></div></div>`).join('')+`<button class="add" id="addWork">+ 개발성과 추가</button>`);
if(current==='archive')h=card('생각 / 아카이브','도서와 글·연구·영상 아카이브 항목을 관리합니다.',`<label>대표 도서명</label>${inp('book.title',data.book.title)}<label>아카이브 — 한 줄에 하나</label>${ta('archive',data.archive.join('\n'))}`);
if(current==='contact')h=card('연락처','공개 사이트 하단 연락처입니다.',`<div class="grid"><div><label>이메일</label>${inp('contact.email',data.contact.email,'email')}</div><div><label>전화</label>${inp('contact.phone',data.contact.phone)}</div></div>`);
if(current==='revisions')h=card('버전 관리','공개할 때마다 이전 공개본을 서버에 보관합니다.',`<div id="revisionList" class="hint">불러오는 중…</div>`);
document.getElementById('panel').innerHTML=h;bind();if(current==='revisions')loadRevisions()}
function pathSet(path,v){const p=path.split('.');let o=data;for(let i=0;i<p.length-1;i++){const k=/^\d+$/.test(p[i])?+p[i]:p[i];o=o[k]}const last=/^\d+$/.test(p.at(-1))?+p.at(-1):p.at(-1);o[last]=v}
function collect(){document.querySelectorAll('[data-k]').forEach(e=>{let v=e.value;if(e.dataset.k==='profile.career'||e.dataset.k==='archive'||/records\.\d+\.items/.test(e.dataset.k))v=v.split('\n').map(x=>x.trim()).filter(Boolean);pathSet(e.dataset.k,v)});localStorage.setItem(KEY,JSON.stringify(data))}
async function fileData(file,cb,folder='uploads'){try{if(V12_CLOUD.ready()){const x=await V12_CLOUD.uploadImage(file,folder);const url=typeof x==='string'?x:(x?.url||x?.publicUrl);if(!url)throw new Error('업로드된 이미지의 공개 URL을 받지 못했습니다.');cb(url);return}if(file.size>1500000&&!confirm('이미지가 큽니다. 브라우저 저장공간을 많이 사용할 수 있습니다. 계속할까요?'))return;const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)}catch(e){alert('이미지 업로드 실패: '+e.message)}}
function bind(){document.querySelectorAll('[data-k]').forEach(e=>e.oninput=()=>{let v=e.value;if(e.dataset.k==='profile.career'||e.dataset.k==='archive'||/records\.\d+\.items/.test(e.dataset.k))v=v.split('\n').map(x=>x.trim()).filter(Boolean);pathSet(e.dataset.k,v)});const pf=document.getElementById('portraitFile');if(pf)pf.onchange=e=>{const f=e.target.files[0];if(f)fileData(f,x=>{data.profile.portrait=x;collect();panel()},'profile')};document.getElementById('clearPortrait')?.addEventListener('click',()=>{data.profile.portrait='';collect();panel()});document.querySelectorAll('input[data-workfile]').forEach(input=>input.onchange=async ev=>{const f=ev.currentTarget.files?.[0],i=Number(ev.currentTarget.dataset.workfile);if(!f)return;if(!Number.isInteger(i)||!data.works?.[i]){alert('포트폴리오 이미지 항목을 확인할 수 없습니다.');return}input.disabled=true;await fileData(f,url=>{data.works[i].image=url;localStorage.setItem(KEY,JSON.stringify(data));panel()},'portfolio')});document.querySelectorAll('[data-delrecord]').forEach(b=>b.onclick=()=>{data.records.splice(+b.dataset.delrecord,1);collect();panel()});document.querySelectorAll('[data-delcourse]').forEach(b=>b.onclick=()=>{data.courses.splice(+b.dataset.delcourse,1);collect();panel()});document.querySelectorAll('[data-delwork]').forEach(b=>b.onclick=()=>{data.works.splice(+b.dataset.delwork,1);collect();panel()});document.getElementById('addRecord')?.addEventListener('click',()=>{data.records.push({year:'',theme:'',items:[]});panel()});document.getElementById('addCourse')?.addEventListener('click',()=>{data.courses.push({name:'',target:'',hours:''});panel()});document.getElementById('addWork')?.addEventListener('click',()=>{data.works.push({title:'',desc:'',image:''});panel()})}
async function saveDraftCloud(){collect();localStorage.setItem(DRAFT,JSON.stringify(data));if(V12_CLOUD.ready())await V12_CLOUD.saveDraft(data)}
document.getElementById('saveDraft').onclick=async()=>{try{await saveDraftCloud();document.getElementById('status').textContent='임시저장 · '+new Date().toLocaleTimeString('ko-KR')}catch(e){alert('저장 실패: '+e.message)}};
document.getElementById('preview').onclick=async()=>{try{await saveDraftCloud();window.open('../?preview=1','_blank')}catch(e){alert('미리보기 저장 실패: '+e.message)}};
document.getElementById('publish').onclick=async()=>{if(!confirm('현재 내용을 공개 사이트에 반영할까요?'))return;try{collect();if(V12_CLOUD.ready())await V12_CLOUD.publish(data,{source:'V12 CMS'});localStorage.setItem(PUB,JSON.stringify(data));localStorage.setItem(DRAFT,JSON.stringify(data));document.getElementById('status').textContent='공개 완료 · '+new Date().toLocaleTimeString('ko-KR')}catch(e){alert('공개 실패: '+e.message)}};
document.getElementById('export').onclick=()=>{collect();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='park-sangdeuk-v12-data.json';a.click();URL.revokeObjectURL(a.href)};
document.getElementById('import').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);localStorage.setItem(KEY,JSON.stringify(data));panel()}catch(err){alert('올바른 JSON 파일이 아닙니다.')}};r.readAsText(f)};
async function loadRevisions(){const el=document.getElementById('revisionList');if(!el)return;if(!V12_CLOUD.ready()){el.textContent='Supabase 연결 후 사용할 수 있습니다.';return}try{const xs=await V12_CLOUD.revisions();el.innerHTML=xs.length?xs.map(x=>`<div class="revision-row"><div><b>${new Date(x.published_at).toLocaleString('ko-KR')}</b><small>Revision #${x.id}</small></div><button class="add" data-restore="${x.id}">초안으로 복원</button></div>`).join(''):'아직 공개 이력이 없습니다.';el.querySelectorAll('[data-restore]').forEach(b=>b.onclick=async()=>{if(!confirm('이 버전을 현재 초안으로 복원할까요?'))return;data=await V12_CLOUD.restoreRevision(b.dataset.restore);localStorage.setItem(KEY,JSON.stringify(data));current='dashboard';panel();alert('초안으로 복원했습니다. 공개 사이트에는 아직 반영되지 않았습니다.')})}catch(e){el.textContent='버전 목록 오류: '+e.message}}
async function boot(){const url=document.getElementById('sbUrl'),key=document.getElementById('sbKey'),gate=document.getElementById('loginGate'),main=document.getElementById('cmsMain'),status=document.getElementById('loginStatus');const c=V12_CLOUD.cfg();url.value=c.url||'';key.value=c.anonKey||'';if(V12_CLOUD.ready()&&await V12_CLOUD.restoreSession()){gate.hidden=true;main.hidden=false;await init();return}document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();status.textContent='로그인 확인 중…';try{V12_CLOUD.saveConfig({url:url.value.trim(),anonKey:key.value.trim()});await V12_CLOUD.signIn(document.getElementById('loginEmail').value.trim(),document.getElementById('loginPassword').value);gate.hidden=true;main.hidden=false;await init()}catch(err){status.textContent=err.message}}}
document.getElementById('logout').onclick=()=>{V12_CLOUD.signOut();location.reload()};boot();