const KEY='psV12CMS',DRAFT='psV12CMSDraft',PUB='psV12CMSPublished';let data,current='dashboard';
const tabs=[['dashboard','대시보드'],['profile','프로필/사진'],['problems','문제인식'],['records','주요실적'],['method','방법론/KAIM'],['courses','교육과정'],['works','개발성과/이미지'],['experience','전문성/현장경험'],['thinking','생각/철학'],['connect','협력/연결'],['portfolio','포트폴리오 정보'],['archive','아카이브'],['contact','연락처'],['revisions','버전관리']];

const EXTRA_DEFAULTS={
experience:{lead:'현장 중심의 문제 인식을 바탕으로, 지방자치단체의 교육·연구·정책 개발을 수행하며 실효성 있는 현장 문제 해결 역량을 다져왔습니다.',professional:'한국공공자치연구원\n국가안보전략연구원\n한국능률협회 등',field:'지방자치단체 공무원 역량 강화 교육 및 특강\n지자체 경영평가 및 지방공기업·지방자치 경영활동 진단\n정책 연구 용역 및 지자체 발전 과제 수립\nAI 행정혁신 컨설팅 및 실무 시스템 구축\n지역 맞춤형 정책 개발 및 자문·심의 활동',expertise:'AI 기반 행정혁신 및 공공 AX(인공지능전환)\n지역 맞춤형 정책 기획 및 과제 발굴\n지능형 업무 프로세스 자동화(IPA) 및 실무 혁신\n공공기관 AI 활용 체계 구축 및 BPR(업무재설계)'},
thinking:{headline:'AI가 사람 대신 일을 하는 시대,\n사람에게 남는 가치는 무엇인가?',items:[{title:'AI와 행정혁신',desc:'AI를 단순한 기능적 자동화 수단을 넘어, 행정 프로세스와 일하는 방식을 근본적으로 혁신하는 핵심 기제로 재정의합니다.'},{title:'AI 역량 강화 방향',desc:'단순한 도구(Tool) 활용 교육을 지양하고, AI를 활용하여 행정 현안을 분석하고 주도적으로 해결하는 문제 해결 역량 배양에 집중합니다.'},{title:'인간 중심의 AI 활용',desc:'AI의 역할이 확대될수록, 대체 불가능한 공직자 고유의 가치(맥락 해석, 공감, 윤리적 판단 등)인 휴먼 프리미엄의 중요성을 강조합니다.'},{title:'지향하는 지방정부 모델',desc:'AI 도입을 넘어, 이를 기반으로 혁신적인 정책을 기획하고 고도화된 행정 서비스를 창출하는 지능형 지방정부로의 도약을 지원합니다.'}],humanTitle:'AI가 확대될수록 인간의 고유한 가치가 더 중요해집니다.',humanDesc:'기술을 도입하는 것에서 끝나지 않고, 사람과 조직의 일하는 방식을 다시 설계하는 이유입니다.'},
connect:{lead:'지방정부의 성공적인 AI 행정혁신과 실효성 있는 정책 개발을 위해 지속적인 협력과 소통의 장을 열어두고 있습니다.',items:[{label:'EDUCATION',title:'공공 역량 강화 교육',desc:'AI 행정혁신 실무, 정책 기획 역량 및 지능형 업무 프로세스 구축 교육'},{label:'RESEARCH',title:'정책 및 행정 연구',desc:'지역 특성화 전략 및 지방정부 중심의 실효적 정책 과제 연구 수행'},{label:'PROJECT',title:'AI 행정혁신 컨설팅',desc:'조직별 맞춤형 AI 활용 체계 구축 및 BPR(업무재설계) 기반 행정 혁신 설계'},{label:'COLLABORATION',title:'파트너십 및 공동 수행',desc:'공공기관·연구기관·교육기관 및 각 분야 전문가와의 다각적 연계 및 공동 프로젝트 추진'}],closing:'지능정보화 시대의 행정혁신은 단순한 기술 도입을 넘어, 사람과 조직의 일하는 방식 전반의 체질개선을 동반해야 합니다. 행정 현장의 실질적인 변화를 함께 이끌어갈 수 있기를 기대합니다.'},
portfolio:{leadTitle:'현장에 적용해 온 교육과 개발 자산',leadDesc:'기존 포트폴리오에 수록된 교육과정·교재·실습도구·진단모형의 내용을 V12의 서사에 맞춰 재배치했습니다.',courseLabel:'교육과정',courseValue:'6개 프로그램',courseNote:'기존 포트폴리오에 명시된 과정군',bookLabel:'저작',bookNote:'기존 사이트 아카이브 항목'}};
function ensureExtra(d){for(const k of Object.keys(EXTRA_DEFAULTS))if(!d[k])d[k]=JSON.parse(JSON.stringify(EXTRA_DEFAULTS[k]));return d}

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const clone=x=>JSON.parse(JSON.stringify(x));
async function init(){
 const local=localStorage.getItem(KEY);data=local?JSON.parse(local):await (await fetch('../data/site-default.json')).json();
 if(V12_CLOUD.ready()){try{const d=await V12_CLOUD.getDraft();if(d?.content)data=d.content;document.getElementById('cloudStatus').textContent='Supabase 연결 · 관리자 인증 완료'}catch(e){document.getElementById('cloudStatus').textContent='Cloud 초안 불러오기 실패'}}
 data=ensureExtra(data);
 document.getElementById('tabs').innerHTML=tabs.map(([k,n])=>`<button data-tab="${k}">${n}</button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{collect();current=b.dataset.tab;panel()});panel()
}
function inp(k,v,type='text'){return `<input data-k="${k}" type="${type}" value="${esc(v)}">`}function ta(k,v){return `<textarea data-k="${k}">${esc(v)}</textarea>`}function card(title,hint,body){return `<div class="card"><h2>${title}</h2><p class="hint">${hint}</p>${body}</div>`}
function panel(){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===current));let h='';
if(current==='dashboard')h=`<div class="dashboard"><div class="dash">교육·워크숍<strong>${esc(data.recordCount)}</strong><span>실시 회차</span></div><div class="dash">교육과정<strong>${data.courses.length}</strong><span>프로그램</span></div><div class="dash">개발성과<strong>${data.works.length}</strong><span>관리 항목</span></div><div class="dash">프로필 사진<strong>${data.profile.portrait?'등록':'미등록'}</strong><span>이미지 상태</span></div></div>`;
if(current==='profile')h=card('프로필 / 이미지','프로필 사진과 로고를 업로드하고 첫 화면의 핵심 문구를 관리합니다.',`<div class="uploadbox"><div class="preview">${data.profile.portrait?`<img src="${esc(data.profile.portrait)}">`:'사진 없음'}</div><div><label>프로필 사진</label><input id="portraitFile" type="file" accept="image/*"><button class="add" id="clearPortrait">사진 삭제</button><label>이름</label>${inp('profile.name',data.profile.name)}<label>영문/키커</label>${inp('profile.kicker',data.profile.kicker)}<label>메인 문장</label>${ta('profile.headline',data.profile.headline)}<label>소개</label>${ta('profile.lead',data.profile.lead)}<label>경력 — 한 줄에 하나</label>${ta('profile.career',data.profile.career.join('\n'))}<label>로고 이미지 경로</label>${inp('profile.logo',data.profile.logo)}</div></div>`);
if(current==='problems')h=card('행정의 문제인식','4개의 문제와 연결 문장을 수정합니다.',data.problems.map((x,i)=>`<div class="grid"><div><label>${i+1}. 제목</label>${inp(`problems.${i}.title`,x.title)}</div><div><label>설명</label>${ta(`problems.${i}.desc`,x.desc)}</div></div>`).join('')+`<label>핵심 연결 문장</label>${inp('problemBridge',data.problemBridge)}`);
if(current==='records')h=card('주요 실적','연도별 테마와 실적을 관리합니다. 실적은 한 줄에 하나씩 입력합니다.',data.records.map((x,i)=>`<div class="row record"><div>${inp(`records.${i}.year`,x.year)}</div><div>${inp(`records.${i}.theme`,x.theme)}</div><div>${ta(`records.${i}.items`,x.items.join('\n'))}</div><button class="del" data-delrecord="${i}">삭제</button></div>`).join('')+`<button class="add" id="addRecord">+ 연도 추가</button><label>총 실시 회차</label>${inp('recordCount',data.recordCount)}`);
if(current==='method')h=card('방법론 / KAIM','5단계 방법론과 KAIM 설명을 관리합니다.',data.method.map((x,i)=>`<label>제${i+1}단계</label>${inp(`method.${i}`,x)}`).join('')+`<label>KAIM 제목</label>${inp('kaim.title',data.kaim.title)}<label>KAIM 설명</label>${ta('kaim.desc',data.kaim.desc)}`);
if(current==='courses')h=card('교육과정','과정명·대상·시간을 관리합니다.',data.courses.map((x,i)=>`<div class="row"><div>${inp(`courses.${i}.name`,x.name)}</div><div>${inp(`courses.${i}.target`,x.target)}</div><div>${inp(`courses.${i}.hours`,x.hours)}</div><span></span><button class="del" data-delcourse="${i}">삭제</button></div>`).join('')+`<button class="add" id="addCourse">+ 과정 추가</button>`);
if(current==='works')h=card('개발성과 / 포트폴리오 이미지','각 개발성과에 대표 이미지를 업로드할 수 있습니다.',data.works.map((x,i)=>`<div class="card"><div class="uploadbox"><div class="preview workpreview">${x.image?`<img src="${esc(x.image)}">`:'이미지 없음'}</div><div><label>제목</label>${inp(`works.${i}.title`,x.title)}<label>설명</label>${ta(`works.${i}.desc`,x.desc)}<label>대표 이미지</label><input type="file" accept="image/*" data-workfile="${i}"><button class="del" data-delwork="${i}">항목 삭제</button></div></div></div>`).join('')+`<button class="add" id="addWork">+ 개발성과 추가</button>`);

if(current==='experience')h=card('06 · 전문성과 현장 경험','전문 경력·현장 경험·전문 영역을 수정합니다.',`<label>섹션 소개</label>${ta('experience.lead',data.experience.lead)}<div class="grid"><div><label>전문 경력 — 한 줄에 하나</label>${ta('experience.professional',data.experience.professional)}</div><div><label>현장 경험 — 한 줄에 하나</label>${ta('experience.field',data.experience.field)}</div></div><label>전문 영역 — 한 줄에 하나</label>${ta('experience.expertise',data.experience.expertise)}`);
if(current==='thinking')h=card('07 · 생각과 철학','4개 Thinking 항목과 Human Premium을 수정합니다.',`<label>메인 질문</label>${ta('thinking.headline',data.thinking.headline)}${data.thinking.items.map((x,i)=>`<div class="grid"><div><label>${i+1}. 제목</label>${inp(`thinking.items.${i}.title`,x.title)}</div><div><label>설명</label>${ta(`thinking.items.${i}.desc`,x.desc)}</div></div>`).join('')}<label>Human Premium 핵심 문장</label>${ta('thinking.humanTitle',data.thinking.humanTitle)}<label>Human Premium 설명</label>${ta('thinking.humanDesc',data.thinking.humanDesc)}`);
if(current==='connect')h=card('08 · 미래 협력과 연결','협력 분야 4개와 Closing 문구를 수정합니다.',`<label>섹션 소개</label>${ta('connect.lead',data.connect.lead)}${data.connect.items.map((x,i)=>`<div class="card"><div class="grid"><div><label>영문 라벨</label>${inp(`connect.items.${i}.label`,x.label)}</div><div><label>제목</label>${inp(`connect.items.${i}.title`,x.title)}</div></div><label>설명</label>${ta(`connect.items.${i}.desc`,x.desc)}</div>`).join('')}<label>마지막 Closing 문구</label>${ta('connect.closing',data.connect.closing)}`);
if(current==='portfolio')h=card('포트폴리오 정보','개발성과 상단 요약 영역을 수정합니다.',`<label>대표 제목</label>${inp('portfolio.leadTitle',data.portfolio.leadTitle)}<label>설명</label>${ta('portfolio.leadDesc',data.portfolio.leadDesc)}<div class="grid"><div><label>교육과정 라벨</label>${inp('portfolio.courseLabel',data.portfolio.courseLabel)}<label>교육과정 값</label>${inp('portfolio.courseValue',data.portfolio.courseValue)}<label>교육과정 주석</label>${inp('portfolio.courseNote',data.portfolio.courseNote)}</div><div><label>저작 라벨</label>${inp('portfolio.bookLabel',data.portfolio.bookLabel)}<label>대표 도서명</label>${inp('book.title',data.book.title)}<label>저작 주석</label>${inp('portfolio.bookNote',data.portfolio.bookNote)}</div></div>`);

if(current==='archive')h=card('생각 / 아카이브','도서와 글·연구·영상 아카이브 항목을 관리합니다.',`<label>대표 도서명</label>${inp('book.title',data.book.title)}<label>아카이브 — 한 줄에 하나</label>${ta('archive',data.archive.join('\n'))}`);
if(current==='contact')h=card('연락처','공개 사이트 하단 연락처입니다.',`<div class="grid"><div><label>이메일</label>${inp('contact.email',data.contact.email,'email')}</div><div><label>전화</label>${inp('contact.phone',data.contact.phone)}</div></div>`);
if(current==='revisions')h=card('버전 관리','공개할 때마다 이전 공개본을 서버에 보관합니다.',`<div id="revisionList" class="hint">불러오는 중…</div>`);
document.getElementById('panel').innerHTML=h;bind();if(current==='revisions')loadRevisions()}
function pathSet(path,v){const p=path.split('.');let o=data;for(let i=0;i<p.length-1;i++){const k=/^\d+$/.test(p[i])?+p[i]:p[i];o=o[k]}const last=/^\d+$/.test(p.at(-1))?+p.at(-1):p.at(-1);o[last]=v}
function collect(){document.querySelectorAll('[data-k]').forEach(e=>{let v=e.value;if(e.dataset.k==='profile.career'||e.dataset.k==='archive'||/records\.\d+\.items/.test(e.dataset.k))v=v.split('\n').map(x=>x.trim()).filter(Boolean);pathSet(e.dataset.k,v)});localStorage.setItem(KEY,JSON.stringify(data))}
async function fileData(file,cb,folder='uploads'){try{if(V12_CLOUD.ready()){const x=await V12_CLOUD.uploadImage(file,folder);const url=typeof x==='string'?x:(x?.url||x?.publicUrl);if(!url)throw new Error('업로드된 이미지의 공개 URL을 받지 못했습니다.');cb(url);return}if(file.size>1500000&&!confirm('이미지가 큽니다. 브라우저 저장공간을 많이 사용할 수 있습니다. 계속할까요?'))return;const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)}catch(e){alert('이미지 업로드 실패: '+e.message)}}
function bind(){document.querySelectorAll('[data-k]').forEach(e=>e.oninput=()=>{let v=e.value;if(e.dataset.k==='profile.career'||e.dataset.k==='archive'||/records\.\d+\.items/.test(e.dataset.k))v=v.split('\n').map(x=>x.trim()).filter(Boolean);pathSet(e.dataset.k,v)});const pf=document.getElementById('portraitFile');if(pf)pf.onchange=e=>{const f=e.target.files[0];if(f)fileData(f,x=>{data.profile.portrait=x;collect();panel()},'profile')};document.getElementById('clearPortrait')?.addEventListener('click',()=>{data.profile.portrait='';collect();panel()});document.querySelectorAll('input[data-workfile]').forEach(input=>input.onchange=async ev=>{const f=ev.currentTarget.files?.[0],i=Number(ev.currentTarget.dataset.workfile);if(!f)return;if(!Number.isInteger(i)||!data.works?.[i]){alert('포트폴리오 이미지 항목을 확인할 수 없습니다.');return}input.disabled=true;await fileData(f,url=>{data.works[i].image=url;localStorage.setItem(KEY,JSON.stringify(data));panel()},'portfolio')});document.querySelectorAll('[data-delrecord]').forEach(b=>b.onclick=()=>{data.records.splice(+b.dataset.delrecord,1);collect();panel()});document.querySelectorAll('[data-delcourse]').forEach(b=>b.onclick=()=>{data.courses.splice(+b.dataset.delcourse,1);collect();panel()});document.querySelectorAll('[data-delwork]').forEach(b=>b.onclick=()=>{data.works.splice(+b.dataset.delwork,1);collect();panel()});document.getElementById('addRecord')?.addEventListener('click',()=>{data.records.push({year:'',theme:'',items:[]});panel()});document.getElementById('addCourse')?.addEventListener('click',()=>{data.courses.push({name:'',target:'',hours:''});panel()});document.getElementById('addWork')?.addEventListener('click',()=>{data.works.push({title:'',desc:'',image:''});panel()})}
async function saveDraftCloud(){collect();localStorage.setItem(DRAFT,JSON.stringify(data));if(V12_CLOUD.ready())await V12_CLOUD.saveDraft(data)}
document.getElementById('saveDraft').onclick=async()=>{try{await saveDraftCloud();document.getElementById('status').textContent='임시저장 · '+new Date().toLocaleTimeString('ko-KR')}catch(e){alert('저장 실패: '+e.message)}};
document.getElementById('preview').onclick=async()=>{try{await saveDraftCloud();window.open('../?preview=1','_blank')}catch(e){alert('미리보기 저장 실패: '+e.message)}};
document.getElementById('publish').onclick=async()=>{if(!confirm('현재 내용을 공개 사이트에 반영할까요?'))return;try{collect();if(V12_CLOUD.ready())await V12_CLOUD.publish(data,{source:'V12 CMS'});localStorage.setItem(PUB,JSON.stringify(data));localStorage.setItem(DRAFT,JSON.stringify(data));document.getElementById('status').textContent='공개 완료 · '+new Date().toLocaleTimeString('ko-KR')}catch(e){alert('공개 실패: '+e.message)}};
document.getElementById('export').onclick=()=>{collect();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='park-sangdeuk-v12-data.json';a.click();URL.revokeObjectURL(a.href)};
document.getElementById('import').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=ensureExtra(JSON.parse(r.result));localStorage.setItem(KEY,JSON.stringify(data));panel()}catch(err){alert('올바른 JSON 파일이 아닙니다.')}};r.readAsText(f)};
async function loadRevisions(){const el=document.getElementById('revisionList');if(!el)return;if(!V12_CLOUD.ready()){el.textContent='Supabase 연결 후 사용할 수 있습니다.';return}try{const xs=await V12_CLOUD.revisions();el.innerHTML=xs.length?xs.map(x=>`<div class="revision-row"><div><b>${new Date(x.published_at).toLocaleString('ko-KR')}</b><small>Revision #${x.id}</small></div><button class="add" data-restore="${x.id}">초안으로 복원</button></div>`).join(''):'아직 공개 이력이 없습니다.';el.querySelectorAll('[data-restore]').forEach(b=>b.onclick=async()=>{if(!confirm('이 버전을 현재 초안으로 복원할까요?'))return;data=ensureExtra(await V12_CLOUD.restoreRevision(b.dataset.restore));localStorage.setItem(KEY,JSON.stringify(data));current='dashboard';panel();alert('초안으로 복원했습니다. 공개 사이트에는 아직 반영되지 않았습니다.')})}catch(e){el.textContent='버전 목록 오류: '+e.message}}
async function boot(){const url=document.getElementById('sbUrl'),key=document.getElementById('sbKey'),gate=document.getElementById('loginGate'),main=document.getElementById('cmsMain'),status=document.getElementById('loginStatus');const c=V12_CLOUD.cfg();url.value=c.url||'';key.value=c.anonKey||'';if(V12_CLOUD.ready()&&await V12_CLOUD.restoreSession()){gate.hidden=true;main.hidden=false;await init();return}document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();status.textContent='로그인 확인 중…';try{V12_CLOUD.saveConfig({url:url.value.trim(),anonKey:key.value.trim()});await V12_CLOUD.signIn(document.getElementById('loginEmail').value.trim(),document.getElementById('loginPassword').value);gate.hidden=true;main.hidden=false;await init()}catch(err){status.textContent=err.message}}}
document.getElementById('logout').onclick=()=>{V12_CLOUD.signOut();location.reload()};boot();