(function(){
 let client=null,session=null;
 const cfg=()=>window.CMS_CLOUD?.config?.()||{url:'',anonKey:''};
 const status=t=>{const e=document.getElementById('cloudStatus');if(e)e.textContent=t; const s=document.getElementById('status');if(s)s.textContent=t};
 async function init(){const c=cfg();if(!c.url||!c.anonKey){status('클라우드 설정 없음 · 현재 로컬 모드');return false}if(!window.supabase){status('Supabase 라이브러리 로드 대기 중');return false}client=window.supabase.createClient(c.url,c.anonKey);const r=await client.auth.getSession();session=r.data.session;window.CMS_CLOUD?.setToken(session?.access_token||'');status(session?'로그인됨: '+(session.user.email||'관리자'):'로그인 필요');return true}
 async function login(){if(!await init())return;const email=document.getElementById('cloudEmail').value.trim(),password=document.getElementById('cloudPassword').value;if(!email||!password){status('이메일과 비밀번호를 입력하세요.');return}const r=await client.auth.signInWithPassword({email,password});if(r.error){status('로그인 실패: '+r.error.message);return}session=r.data.session;window.CMS_CLOUD?.setToken(session?.access_token||'');document.getElementById('cloudPassword').value='';status('로그인됨: '+email);bindWorkflow();}
 async function logout(){if(client)await client.auth.signOut();session=null;window.CMS_CLOUD?.setToken('');status('로그아웃됨');}
 function saveConfig(){const c={url:document.querySelector('[data-k="cloud.url"]').value.trim().replace(/\/$/,''),anonKey:document.querySelector('[data-k="cloud.anonKey"]').value.trim()};window.CMS_CLOUD.saveConfig(c);status(c.url?'설정 저장됨. 로그인하세요.':'로컬 모드');init();}
 function localPayload(){return {data:JSON.parse(localStorage.getItem('labPortfolioCMS')||'{}'),text:JSON.parse(localStorage.getItem('labPortfolioUniversal')||'{}'),images:JSON.parse(localStorage.getItem('labPortfolioImages')||'{}')}}
 function summary(){return {generated_at:new Date().toISOString(),note:'CMS publish'}}
 async function pull(){if(!window.CMS_CLOUD?.ready()){status('클라우드 설정을 먼저 저장하세요.');return}try{const row=await window.CMS_CLOUD.getState(session?.access_token);if(!row){status('공개 데이터가 없습니다.');return}if(row.published_data){localStorage.setItem('labPortfolioCMSPublished',JSON.stringify(row.published_data));localStorage.setItem('labPortfolioCMS',JSON.stringify(row.published_data));data=JSON.parse(JSON.stringify(row.published_data))}if(row.published_text){localStorage.setItem('labPortfolioUniversalPublished',JSON.stringify(row.published_text));localStorage.setItem('labPortfolioUniversal',JSON.stringify(row.published_text))}if(row.published_images){localStorage.setItem('labPortfolioImagesPublished',JSON.stringify(row.published_images));localStorage.setItem('labPortfolioImages',JSON.stringify(row.published_images))}if(row.draft_data&&Object.keys(row.draft_data).length){localStorage.setItem('labPortfolioCMSDraft',JSON.stringify(row.draft_data))}panel();status('클라우드 공개본을 불러왔습니다.')}catch(e){status('불러오기 실패: '+e.message)}}
 async function cloudDraft(){if(!session){status('먼저 관리자 로그인을 하세요.');return false}try{collect();save();const p=localPayload();await window.CMS_CLOUD.saveDraft(p,session.access_token);localStorage.setItem('labPortfolioCMSDraft',JSON.stringify(p.data));localStorage.setItem('labPortfolioUniversalDraft',JSON.stringify(p.text));localStorage.setItem('labPortfolioImagesDraft',JSON.stringify(p.images));status('클라우드 임시저장 완료 · '+new Date().toLocaleTimeString('ko-KR'));return true}catch(e){status('클라우드 임시저장 실패: '+e.message);return false}}
 async function cloudPublish(){if(!session){status('먼저 관리자 로그인을 하세요.');return}if(!confirm('현재 콘텐츠를 클라우드에 공개할까요? 공개 전 현재 공개본은 서버 변경이력에 보관됩니다.'))return;try{await cloudDraft();const p=localPayload();await window.CMS_CLOUD.publishState(p,summary(),session.access_token,session.user.id);localStorage.setItem('labPortfolioCMSPublished',JSON.stringify(p.data));localStorage.setItem('labPortfolioUniversalPublished',JSON.stringify(p.text));localStorage.setItem('labPortfolioImagesPublished',JSON.stringify(p.images));status('클라우드 공개 완료 · '+new Date().toLocaleTimeString('ko-KR'));}catch(e){status('클라우드 공개 실패: '+e.message)}}
 async function showRevisions(){const box=document.getElementById('cloudHistoryBox');if(!box)return;if(!session){box.innerHTML='<p class="small-muted">관리자 로그인 후 변경 이력을 확인할 수 있습니다.</p>';return}try{const rows=await window.CMS_CLOUD.revisions(session.access_token);box.innerHTML='<div class="history-head"><div><b>서버 변경 이력</b><span class="small-muted">Supabase에 저장된 공개본</span></div></div>'+(rows.length?rows.map((r,i)=>`<div class="history-item"><div><strong>${i+1}. ${new Date(r.published_at).toLocaleString('ko-KR')}</strong><div class="small-muted">${esc(r.published_by||'관리자')}</div></div><div class="history-buttons"><button data-cloud-restore="${r.id}" class="restore">이 버전 복구</button></div></div>`).join(''):'<p class="small-muted">서버 변경 이력이 없습니다.</p>');box.querySelectorAll('[data-cloud-restore]').forEach(b=>b.onclick=()=>restore(Number(b.dataset.cloudRestore)));}catch(e){box.innerHTML='<p class="small-muted">이력 조회 실패: '+esc(e.message)+'</p>'}}
 async function restore(id){if(!confirm('선택한 서버 버전을 현재 작업본으로 복구할까요? 공개되지는 않습니다.'))return;try{await window.CMS_CLOUD.restoreRevision(id,session.access_token);await pull();status('서버 버전을 작업본으로 복구했습니다. 미리보기 후 공개하세요.')}catch(e){status('복구 실패: '+e.message)}}
 function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function bindWorkflow(){
   const d=document.getElementById('saveDraft'),p=document.getElementById('publishSite'),h=document.getElementById('historySite');
   if(d&&!d.dataset.cloudBound){d.dataset.cloudBound='1';d.onclick=e=>{if(session){e.preventDefault();cloudDraft()}else{e.target.blur()}}}
   if(p&&!p.dataset.cloudBound){p.dataset.cloudBound='1';p.onclick=e=>{if(session){e.preventDefault();cloudPublish()}}}
   if(h&&!h.dataset.cloudBound){h.dataset.cloudBound='1';h.onclick=e=>{if(session){e.preventDefault();showRevisions()}else{document.getElementById('historySite')?.dispatchEvent(new Event('click'))}}}
 }
 let initialized=false; window.CMS_ADMIN_CLOUD={bind(){if(!initialized){initialized=true;document.getElementById('saveCloudConfig')?.addEventListener('click',saveConfig);document.getElementById('cloudLogin')?.addEventListener('click',login);document.getElementById('cloudLogout')?.addEventListener('click',logout);document.getElementById('cloudPull')?.addEventListener('click',pull);document.getElementById('cloudPush')?.addEventListener('click',cloudPublish);init()} bindWorkflow(); if(!document.getElementById('cloudHistoryBox')){const x=document.createElement('div');x.id='cloudHistoryBox';x.className='history-box';document.querySelector('.actions')?.after(x)}}};
})();
