/* Current editors use the original data, save, publish and history handlers. */
tabs.splice(0,tabs.length,['dashboard','관리 안내'],['profile','01 소개와 문제의식'],['experience','02 전문성과 경험'],['records','03 수행 기록'],['problems','04 행정 AI 관점'],['outputs','05 저서·지식자산'],['hub','06 Learning Hub'],['footer','하단 채널'],['revisions','버전 관리']);
EXTRA_DEFAULTS.experience=PS_STORY_DEFAULTS.experience;
const previousEnsure=ensureExtra;ensureExtra=d=>PS_CURRENT.ensure(previousEnsure(d));
const previousPanel=panel;
const field=(label,key,value,multi=false)=>`<div class="field"><label>${esc(label)}</label>${multi?ta(key,value):inp(key,value)}</div>`;
const heading=id=>{const s=data.presentation.sections[id];return field('구간 제목',`presentation.sections.${id}.title`,s.title,true)};
const checks=(k,v,label)=>`<label class="asset-check"><input type="checkbox" data-k="${k}" ${v?'checked':''}>${esc(label)}</label>`;
const categories=[['Education Programs','교육과정'],['Learning Materials','교재'],['Practice Tools','실습도구'],['Administrative Tools','행정지원도구'],['Diagnostic & Content Tools','진단·콘텐츠 도구']];
const choice=(k,v,values)=>`<select data-k="${k}">${values.map(([x,n])=>`<option value="${esc(x)}" ${x===v?'selected':''}>${esc(n)}</option>`).join('')}</select>`;
panel=function(){
data=PS_CURRENT.ensure(data);let h='';
if(current==='dashboard')h=card('현재 포트폴리오 관리','공개 화면과 같은 순서입니다. 바꿀 내용이 있는 구간을 선택하세요.',`<div class="editor-map">${tabs.filter(([k])=>!['dashboard','revisions'].includes(k)).map(([k,n])=>`<button data-go="${k}"><b>${esc(n)}</b><span>${esc({profile:'이름 · 사진 · 메인 문장 · 문제와 해결 방향',experience:'소개 · 전문 영역 · 현장 경험',records:'제목 · 소개 · 연도별 이력',problems:'제목 · 네 가지 관점',outputs:'저서 서지정보 · 교육과정 · 자산 목록',hub:'소개 · 이용 안내 · 연결 주소',footer:'브랜드 문구 · 소셜 채널'}[k])}</span></button>`).join('')}</div><p class="hint">수정 → 초안 저장 → 미리보기 → 공개 게시 순서로 진행하세요. 공개되지 않는 과거 항목은 버전 관리의 ‘이전 구성 자료’에서 확인할 수 있습니다.</p>`);
if(current==='profile')h=card('01 · 소개와 문제의식','첫 화면에 표시되는 모든 내용을 이곳에서 수정합니다.',field('이름','profile.name',data.profile.name)+field('영문 이름 / 표시 이름','profile.kicker',data.profile.kicker)+field('메인 문장','profile.headline',data.profile.headline,true)+field('짧은 소개','profile.lead',data.profile.lead,true)+field('상단 경력 — 한 줄에 하나','profile.career',data.profile.career.join('\n'),true)+field('문제 제기','presentation.identity.problem',data.presentation.identity.problem,true)+field('해결 방향','presentation.identity.solution',data.presentation.identity.solution,true)+`<div class="uploadbox"><div class="preview">${data.profile.portrait?`<img src="${esc(data.profile.portrait)}" alt="프로필 사진">`:'사진 없음'}</div><div><label>프로필 사진 업로드</label><input id="portraitFile" type="file" accept="image/*"><button class="add" id="clearPortrait">사진 제거</button><p class="hint">사진은 화면의 30% 이내로 표시됩니다.</p></div></div>`);
if(current==='experience')h=card('02 · 전문성과 현장 경험','소개와 두 가지 목록을 수정합니다. 목록은 한 줄에 하나씩 입력하세요.',heading('expertise')+field('소개','experience.lead',data.experience.lead,true)+['expertise','field'].map(k=>field('목록 제목',`presentation.experienceHeadings.${k}`,data.presentation.experienceHeadings[k])+field({professional:'주요 경력',expertise:'핵심 전문 영역',field:'현장 수행 경험'}[k],`experience.${k}`,data.experience[k],true)).join(''));
if(current==='records')h=card('03 · 교육·연구·실행 기록','연도별 기록을 한곳에서 관리합니다. 실적은 한 줄에 하나씩 입력하세요.',heading('records')+field('소개','presentation.sections.records.intro',data.presentation.sections.records.intro,true)+data.records.map((r,i)=>`<div class="editor-item"><div class="grid">${field('연도',`records.${i}.year`,r.year)}${field('연도별 주제',`records.${i}.theme`,r.theme)}</div>${field('수행 기록',`records.${i}.items`,r.items.join('\n'),true)}<button class="del" data-delrecord="${i}">연도 삭제</button></div>`).join('')+'<button class="add" id="addRecord">+ 연도 추가</button>');
if(current==='problems')h=card('04 · 행정 AI에 대한 관점','공개 화면의 제목과 관점별 설명을 수정합니다.',heading('perspective')+data.problems.map((p,i)=>`<div class="editor-item">${field(`${i+1}. 관점 제목`,`problems.${i}.title`,p.title)}${field('설명',`problems.${i}.desc`,p.desc,true)}<button class="del" data-delproblem="${i}">항목 삭제</button></div>`).join('')+'<button class="add" id="addProblem">+ 관점 추가</button>');
if(current==='outputs'){
const s=data.presentation.sections.assets;h=card('05 · 저서와 지식자산','저서 → 교육과정 → 교재·도구 목록 순서입니다. 제목·소개·목록을 이 화면에서 관리합니다.',heading('assets')+field('소개','portfolio.leadDesc',data.portfolio.leadDesc,true));
h+=card('저서','현재 공개 화면에는 제목과 서지정보가 표시됩니다.',field('저서 제목','book.title',data.book.title)+`<div class="grid">${field('출판사','book.publisher',data.book.publisher)}${field('발행일','book.publicationDate',data.book.publicationDate)}</div>`+field('ISBN','book.isbn',data.book.isbn));
h+=card('교육과정 목록','공개 화면에 표시되는 과정명·대상·시간을 수정합니다.',field('목록 제목','presentation.sections.assets.courseHeading',s.courseHeading)+data.courses.map((c,i)=>`<div class="editor-item">${field('과정명',`courses.${i}.name`,c.name)}<div class="grid">${field('대상',`courses.${i}.target`,c.target)}${field('시간',`courses.${i}.hours`,c.hours)}</div><button class="del" data-delcourse="${i}">과정 삭제</button></div>`).join('')+'<button class="add" id="addCourse">+ 교육과정 추가</button>');
h+=card('교재·도구·지식자산 목록','표시 여부를 선택하고 목록의 이름과 분류를 수정하세요. 이전 이미지·파일은 삭제되지 않습니다.',field('목록 제목','presentation.sections.assets.assetHeading',s.assetHeading)+'<label>자산 이름으로 찾기</label><input id="assetSearch" type="search" placeholder="교재·도구 이름 입력">'+data.assets.map((a,i)=>{if(a.category==='Education Programs')return '';const k=`assets.${i}`;return `<details class="editor-item" data-currentasset="${i}"><summary>${esc(a.title)} · ${a.public!==false?'표시':'숨김'}</summary>${field('자산 이름',k+'.title',a.title)}<label>목록 분류</label>${choice(k+'.category',a.category,categories.filter(([c])=>c!=='Education Programs'))}${checks(k+'.public',a.public!==false,'목록에 표시')}${checks(k+'.registered',a.registered,'저작권 등록')}<div class="grid">${field('등록번호',k+'.registrationNumber',a.registrationNumber)}${field('등록일',k+'.registrationDate',a.registrationDate)}</div>${field('등록 저작물명',k+'.registeredTitle',a.registeredTitle)}<button class="del" data-delasset="${i}">자산 삭제</button></details>`}).join('')+'<button class="add" id="addCurrentAsset">+ 교재·도구 추가</button>');
}
if(current==='hub')h=card('06 · Learning Hub','학습공간 소개와 연결 목록을 관리합니다. 연결은 원하는 만큼 추가할 수 있습니다.',heading('hub')+field('Learning Hub 소개','presentation.hub.intro',data.presentation.hub.intro,true)+field('이용 안내','presentation.hub.guide',data.presentation.hub.guide,true)+data.presentation.hub.links.map((l,i)=>`<div class="editor-item">${field('연결 이름',`presentation.hub.links.${i}.label`,l.label)}${field('연결 주소',`presentation.hub.links.${i}.url`,l.url)}<button class="del" data-delhublink="${i}">연결 삭제</button></div>`).join('')+'<button class="add" id="addHubLink">+ 연결 추가</button><p class="hint">이곳에서는 포트폴리오의 소개와 연결을 관리합니다. Learning Hub 내부 콘텐츠와 교육과정 페이지의 관리는 별도입니다.</p>');
if(current==='footer')h=card('하단 브랜드와 채널','공개 화면 맨 아래의 문구와 소셜 링크입니다.',field('표시 이름','presentation.footer.brand',data.presentation.footer.brand)+field('활동 분야','presentation.footer.tagline',data.presentation.footer.tagline)+data.story.channels.map((c,i)=>`<div class="editor-item">${field('채널 이름',`story.channels.${i}.name`,c.name)}${field('채널 주소',`story.channels.${i}.url`,c.url)}<button class="del" data-delchannel="${i}">채널 삭제</button></div>`).join('')+'<button class="add" id="addChannel">+ 채널 추가</button>');
if(current==='revisions'){previousPanel();document.getElementById('panel').insertAdjacentHTML('beforeend',card('이전 구성 자료','과거 구성과 자산 첨부자료를 보관합니다. 자산 이름·표시 여부는 현재 목록과 공유되므로 변경 시 공개 목록에도 반영됩니다.',`<details><summary>이전 구성 자료 열기</summary><div class="legacy-buttons">${[['method','방법론 / KAIM'],['thinking','생각과 철학'],['connect','협력과 연락'],['archive','아카이브'],['works','자산 첨부자료·고급 설정'],['contact','보관 연락처']].map(([k,n])=>`<button data-legacy="${k}">${n}</button>`).join('')}</div></details>`));bindCurrent();return}
if(!h){previousPanel();document.getElementById('panel').insertAdjacentHTML('afterbegin','<div class="notice">보관된 이전 구성 자료입니다. 현재 구간은 번호별 편집 화면에서 관리하세요. 자산의 이름·표시 여부는 현재 목록과 공유됩니다.</div>');return}
document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===current));document.getElementById('panel').innerHTML=h;bind();bindCurrent();
};
function bindCurrent(){document.getElementById('assetSearch')?.addEventListener('input',e=>{const q=e.target.value.trim().toLocaleLowerCase();document.querySelectorAll('[data-currentasset]').forEach(el=>{el.hidden=!data.assets[+el.dataset.currentasset].title.toLocaleLowerCase().includes(q)})});document.querySelectorAll('[data-go],[data-legacy]').forEach(b=>b.onclick=()=>{collect();current=b.dataset.go||b.dataset.legacy;panel()});const add=(id,fn)=>document.getElementById(id)?.addEventListener('click',()=>{collect();fn();panel()});add('addProblem',()=>data.problems.push({title:'새 관점',desc:''}));add('addHubLink',()=>data.presentation.hub.links.push({label:'새 연결',url:''}));document.querySelectorAll('[data-delhublink]').forEach(b=>b.onclick=()=>{collect();data.presentation.hub.links.splice(+b.dataset.delhublink,1);panel()});add('addChannel',()=>data.story.channels.push({name:'새 채널',url:''}));add('addCurrentAsset',()=>data.assets.push({id:'ASSET-'+crypto.randomUUID(),title:'새 교재·도구',category:'Learning Materials',kind:'material',desc:'',use:'',image:'',url:'',featured:false,public:false,registered:false,registeredTitle:'',registrationNumber:'',registrationDate:''}));document.querySelectorAll('[data-delproblem],[data-delchannel]').forEach(b=>b.onclick=()=>{collect();const name=b.dataset.delproblem!==undefined?'problems':'channels',i=+(b.dataset.delproblem??b.dataset.delchannel);(name==='problems'?data.problems:data.story.channels).splice(i,1);panel()})}
const previousValidate=V12_ASSETS.validate;V12_ASSETS.validate=d=>{previousValidate(d);for(const l of d.presentation.hub.links)if(!PS_CURRENT.validURL(l.url))throw Error('Learning Hub의 연결 주소를 확인해 주세요.');for(const c of d.story.channels)if(c.url&&!PS_CURRENT.validURL(c.url))throw Error('하단 채널의 연결 주소를 확인해 주세요.')};
// A restored session can initialize before this script finishes downloading.
if(data){data=ensureExtra(data);document.getElementById('tabs').innerHTML=tabs.map(([k,n])=>`<button data-tab="${k}">${esc(n)}</button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{collect();current=b.dataset.tab;panel()});panel()}
