/* Homepage editing uses the existing signed-in CMS client and administrator RLS. */
(()=>{'use strict';
const fields=[['eyebrow','상단 작은 문구',120],['title','메인 제목',160],['intro','메인 설명',1000],['closingTitle','하단 제목',200],['closingBody','하단 설명',1000],['browseLabel','학습 목록 링크 문구',80],['footer','푸터 표기',160],['websiteLabel','홈페이지 링크 문구',80],['websiteUrl','홈페이지 주소',500]];
const host=document.querySelector('.side-head');if(!host)return;
const launch=document.createElement('button');launch.type='button';launch.className='home-edit-launch';launch.textContent='첫 화면 편집';host.append(launch);
const dialog=document.createElement('dialog');dialog.className='homepage-dialog';dialog.setAttribute('aria-labelledby','homepageEditTitle');
dialog.innerHTML='<div class="homepage-dialog-head"><h2 id="homepageEditTitle">첫 화면 편집</h2><button type="button" aria-label="편집 창 닫기">×</button></div><div class="homepage-fields"><p>초안 저장은 공개 화면을 바꾸지 않습니다. 공개 반영을 누르면 첫 화면에 적용됩니다. 줄바꿈은 입력한 대로 표시됩니다.</p><div id="homepageInputs"></div><h3>트랙 카드 설명</h3><p>트랙 이름은 기존 학습 분야의 이름을 그대로 사용합니다.</p><div id="homepageTrackInputs"></div></div><div class="homepage-dialog-actions"><span class="homepage-status" role="status"></span><button type="button" data-action="draft">초안 저장</button><button type="button" data-action="publish">공개 반영</button></div>';
document.body.append(dialog);const status=dialog.querySelector('.homepage-status');const buttons=[...dialog.querySelectorAll('[data-action]')];
let loaded=false,busy=false,dirty=false,version=null,tracks=[],content={};
function setBusy(value){busy=value;buttons.forEach(b=>b.disabled=value||!loaded)}
function addField(container,key,label,value,max,track){const l=document.createElement('label');l.textContent=label;const input=document.createElement(key==='websiteUrl'||key.endsWith('Label')?'input':'textarea');if(input.tagName==='TEXTAREA')input.rows=key==='intro'||key==='closingBody'?3:2;input.maxLength=max;input.value=value||'';input.dataset.homeKey=key;if(track)input.dataset.track=track;input.addEventListener('input',()=>{dirty=true;status.textContent='미저장 변경'});l.append(input);container.append(l)}
function client(){if(!window.learningHubDb?.client)throw Error('CMS 연결을 찾을 수 없습니다.');return window.learningHubDb.client}
function render(){const a=dialog.querySelector('#homepageInputs'),b=dialog.querySelector('#homepageTrackInputs');a.replaceChildren();b.replaceChildren();fields.forEach(([key,label,max])=>addField(a,key,label,content[key],max));tracks.forEach(t=>addField(b,'trackDescription',t.name,content.trackDescriptions?.[t.track_code]??t.description??'',500,t.track_code));}
async function open(){if(busy)return;if(loaded&&dirty){dialog.showModal();return}dialog.showModal();loaded=false;setBusy(true);status.textContent='불러오는 중…';try{const session=await window.learningHubDb.getSession();if(!session)throw Error('관리자 로그인이 필요합니다.');const [home,track]=await Promise.all([client().from('learning_homepage').select('status,content,updated_at').in('status',['draft','public']),client().from('learning_tracks').select('track_code,name,description').eq('is_active',true).order('sort_order')]);if(home.error)throw home.error;if(track.error)throw track.error;const row=home.data.find(r=>r.status==='draft')||home.data.find(r=>r.status==='public');if(!row)throw Error('첫 화면 설정을 찾을 수 없습니다.');content=JSON.parse(JSON.stringify(row.content));version=row.status==='draft'?row.updated_at:null;tracks=track.data;render();loaded=true;dirty=false;status.textContent='편집 준비 완료';}catch(e){status.textContent='불러오기 실패: '+e.message}finally{setBusy(false)}}
function collect(){const value={...content,trackDescriptions:{...(content.trackDescriptions||{})}};dialog.querySelectorAll('[data-home-key]').forEach(el=>{if(el.dataset.track)value.trackDescriptions[el.dataset.track]=el.value.trim();else value[el.dataset.homeKey]=el.value.trim()});for(const [key,label] of fields)if(!value[key])throw Error(label+'을 입력해 주세요.');let url;try{url=new URL(value.websiteUrl)}catch(_){throw Error('홈페이지 주소를 확인해 주세요.')}if(!['https:','http:'].includes(url.protocol)||url.username||url.password)throw Error('홈페이지는 http 또는 https 주소를 입력해 주세요.');return value}
async function save(publish){if(busy||!loaded)return;let next;try{next=collect()}catch(e){status.textContent=e.message;return}setBusy(true);status.textContent=publish?'공개 반영 중…':'초안 저장 중…';try{const result=await client().rpc('save_learning_homepage',{p_content:next,p_publish:publish,p_expected_updated_at:version});if(result.error)throw result.error;version=result.data;content=next;dirty=false;status.textContent=publish?'공개 반영 완료 · 공개 화면을 새로고침하세요.':'초안을 저장했습니다.';}catch(e){status.textContent='저장하지 않았습니다: '+e.message}finally{setBusy(false)}}
function close(){if(busy)return;if(dirty&&!confirm('저장하지 않은 첫 화면 변경사항을 닫으시겠습니까?'))return;dirty=false;loaded=false;dialog.close()}
launch.addEventListener('click',open);dialog.querySelector('.homepage-dialog-head button').addEventListener('click',close);dialog.addEventListener('cancel',e=>{e.preventDefault();close()});buttons.forEach(b=>b.addEventListener('click',()=>save(b.dataset.action==='publish')));window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});setBusy(false);
})();
