(()=>{'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function prose(body){let out='',rows=[];const flush=()=>{if(rows.length){const schedule=rows[0].length===3&&rows[0][0].trim()==='시간'&&rows[0][1].trim()==='활동'&&rows[0][2].trim()==='방법';const overview=rows[0].length===2&&rows[0][0].replace(/\s/g,'')==='과정명';const curriculum=rows[0].length===4&&rows[0][0].trim()==='구분'&&rows[0][1].trim()==='모듈명';out+='<div class="table-scroll"><table'+(schedule?' class="schedule-table"':curriculum?' class="curriculum-table"':overview?' class="overview-table"':'')+'><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';rows=[];}};for(const line of String(body).split('\n')){if(line.includes('\t')){rows.push(line.split('\t'));continue}flush();if(!line.trim())continue;if(line.startsWith('□'))out+='<h3>'+esc(line.slice(1))+'</h3>';else if(/^제\d+회차\./.test(line))out+='<h3>'+esc(line)+'</h3>';else if(line.startsWith('○')&&line.length<45&&!/[.。]$/.test(line.trim()))out+='<h4>'+esc(line.slice(1))+'</h4>';else if(/^[-○]/.test(line))out+='<p class="bullet-paragraph"><span class="bullet-marker">'+esc(line[0])+'</span>'+esc(line.slice(1).trimStart())+'</p>';else out+='<p>'+esc(line)+'</p>';}flush();return out;}
function safeURL(v){if(!String(v??'').trim())return '';try{const u=new URL(v,location.href);return ['https:','http:'].includes(u.protocol)||(location.protocol==='file:'&&u.protocol==='file:'&&!/^[a-z]+:/i.test(v))?u.href:''}catch{return ''}}
function download(name,data,type='application/json'){const u=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000);}
function notify(s){const n=document.getElementById('notice');n.textContent=s;n.style.display='block';clearTimeout(window.noticeTimer);window.noticeTimer=setTimeout(()=>n.style.display='none',5000)}
function validate(data){if(data?.schemaVersion!==1||!Array.isArray(data.courses)||data.courses.length>100)throw Error('지원하지 않는 과정 데이터입니다.');const ids=new Set();for(const c of data.courses){if(!/^[A-Za-z0-9_-]{1,40}$/.test(c.id)||ids.has(c.id)||!c.title?.trim()||!Array.isArray(c.sections)||c.sections.length>30)throw Error('과정 코드·제목·구성을 확인하세요.');ids.add(c.id);for(const k of ['title','category','audience','capacity','duration','format','schedule','outcome','summary','document','documentLabel'])if(typeof c[k]!=='string')throw Error('필수 과정 정보가 누락되었습니다: '+k);for(const s of c.sections)if(typeof s.title!=='string'||typeof s.body!=='string')throw Error('안내 항목을 확인하세요.');}return data;}
const cfg=window.COURSE_SUPABASE||{};let session=null;try{session=JSON.parse(sessionStorage.getItem('course.auth')||'null')}catch{}
async function request(path,opts={},auth=false){if(!cfg.url||!cfg.anonKey)throw Error('CMS 연결 설정이 필요합니다.');if(auth){if(!session)throw Error('관리자 로그인이 필요합니다.');if(session.expires_at*1000<Date.now()+60000){const r=await fetch(cfg.url+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:cfg.anonKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});const next=await r.json();if(!r.ok){session=null;sessionStorage.removeItem('course.auth');throw Error('로그인이 만료되었습니다. 다시 로그인하세요.')}session=next;sessionStorage.setItem('course.auth',JSON.stringify(session));}}
const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const res=await fetch(cfg.url+path,{...opts,signal:controller.signal,headers:{apikey:cfg.anonKey,...(auth?{Authorization:'Bearer '+session.access_token}:{}),'Content-Type':'application/json',...opts.headers}});const text=await res.text();let data;try{data=text?JSON.parse(text):null}catch{throw Error('서버 응답을 읽을 수 없습니다.')}if(!res.ok)throw Error(data?.message||data?.msg||data?.error_description||'CMS 요청에 실패했습니다.');return data;}catch(e){if(e.name==='AbortError')throw Error('CMS 연결 시간이 초과되었습니다. 다시 시도하세요.');throw e}finally{clearTimeout(timer)}}
const db={configured:!!(cfg.url&&cfg.anonKey),async login(email,password){session=await request('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});sessionStorage.setItem('course.auth',JSON.stringify(session));try{await db.checkAdmin()}catch(e){await db.logout();throw e}},async checkAdmin(){const rows=await request('/rest/v1/cms_admins?select=email',{},true);if(!rows?.length)throw Error('관리자 허용목록에 등록된 계정이 아닙니다.');return true},async logout(){try{if(session)await request('/auth/v1/logout',{method:'POST'},true)}finally{session=null;sessionStorage.removeItem('course.auth')}},hasSession:()=>!!session,async publicData(){const rows=await request('/rest/v1/course_catalog_published?id=eq.main&select=content,version');return rows?.[0]||null},async draft(){return (await request('/rest/v1/course_catalog_drafts?id=eq.main&select=content,version',{},true))?.[0]||null},async save(content,expected){return request('/rest/v1/rpc/course_catalog_save',{method:'POST',body:JSON.stringify({payload:content,expected_version:expected})},true)},async publish(expected){return request('/rest/v1/rpc/course_catalog_publish',{method:'POST',body:JSON.stringify({expected_version:expected})},true)},async revisions(){return request('/rest/v1/course_catalog_revisions?select=id,created_at,content&order=id.desc&limit=20',{},true)}};
db.upload=async file=>{const ext=file.name.split('.').pop().toLowerCase();const name=crypto.randomUUID()+'.'+ext;await request('/storage/v1/object/course-documents/'+name,{method:'POST',headers:{'Content-Type':ext==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document'},body:file},true);return cfg.url+'/storage/v1/object/public/course-documents/'+name};
window.Course={esc,prose,safeURL,download,notify,validate,db};})();
